RMDIR "base\characters\Adachi" /s /y
RMDIR "base\characters\Crogrey" /s /y

del "base\characters\PhoenixSOJ\(a)fuck.gif"
del "base\characters\PhoenixSOJ\(a)itsogre.gif"
del "base\characters\PhoenixSOJ\(a)normal.gif"
del "base\characters\PhoenixSOJ\(a)oops.gif"
del "base\characters\PhoenixSOJ\(a)paper.gif"
del "base\characters\PhoenixSOJ\(a)point.gif"
del "base\characters\PhoenixSOJ\(a)shit.gif"
del "base\characters\PhoenixSOJ\(a)smug.gif"
del "base\characters\PhoenixSOJ\(a)think.gif"
del "base\characters\PhoenixSOJ\(a)urk.gif"
del "base\characters\PhoenixSOJ\(b)fuck.gif"
del "base\characters\PhoenixSOJ\(b)itsogre.gif"
del "base\characters\PhoenixSOJ\(b)normal.gif"
del "base\characters\PhoenixSOJ\(b)oops.gif"
del "base\characters\PhoenixSOJ\(b)paper.gif"
del "base\characters\PhoenixSOJ\(b)point.gif"
del "base\characters\PhoenixSOJ\(b)shit.gif"
del "base\characters\PhoenixSOJ\(b)smug.gif"
del "base\characters\PhoenixSOJ\(b)think.gif"
del "base\characters\PhoenixSOJ\(b)urk.gif"
del "base\characters\PhoenixSOJ\fuck.gif"
del "base\characters\PhoenixSOJ\no.gif"
del "base\characters\PhoenixSOJ\oops.gif"
del "base\characters\PhoenixSOJ\paper.gif"
del "base\characters\PhoenixSOJ\point.gif"
del "base\characters\PhoenixSOJ\shit.gif"
del "base\characters\PhoenixSOJ\slam.gif"
del "base\characters\PhoenixSOJ\smug.gif"
del "base\characters\PhoenixSOJ\think.gif"
del "base\characters\PhoenixSOJ\urk.gif"
del "base\characters\PhoenixSOJ\yes.gif"

del "base\characters\Phoenix Furio\(a)fuck.gif"
del "base\characters\Phoenix Furio\(a)itsogre.gif"
del "base\characters\Phoenix Furio\(a)normal.gif"
del "base\characters\Phoenix Furio\(a)oops.gif"
del "base\characters\Phoenix Furio\(a)paper.gif"
del "base\characters\Phoenix Furio\(a)point.gif"
del "base\characters\Phoenix Furio\(a)shit.gif"
del "base\characters\Phoenix Furio\(a)smug.gif"
del "base\characters\Phoenix Furio\(a)think.gif"
del "base\characters\Phoenix Furio\(a)urk.gif"
del "base\characters\Phoenix Furio\(b)fuck.gif"
del "base\characters\Phoenix Furio\(b)itsogre.gif"
del "base\characters\Phoenix Furio\(b)normal.gif"
del "base\characters\Phoenix Furio\(b)oops.gif"
del "base\characters\Phoenix Furio\(b)paper.gif"
del "base\characters\Phoenix Furio\(b)point.gif"
del "base\characters\Phoenix Furio\(b)shit.gif"
del "base\characters\Phoenix Furio\(b)smug.gif"
del "base\characters\Phoenix Furio\(b)think.gif"
del "base\characters\Phoenix Furio\(b)urk.gif"
del "base\characters\Phoenix Furio\fuck.gif"
del "base\characters\Phoenix Furio\no.gif"
del "base\characters\Phoenix Furio\oops.gif"
del "base\characters\Phoenix Furio\paper.gif"
del "base\characters\Phoenix Furio\point.gif"
del "base\characters\Phoenix Furio\shit.gif"
del "base\characters\Phoenix Furio\slam.gif"
del "base\characters\Phoenix Furio\smug.gif"
del "base\characters\Phoenix Furio\think.gif"
del "base\characters\Phoenix Furio\urk.gif"
del "base\characters\Phoenix Furio\yes.gif"

ren base\characters\Elise\emotions\button8_off.png button1_off.png
ren base\characters\Elise\emotions\button8_on.png button1_on.png
ren base\characters\Elise\emotions\button9_off.png button2_off.png
ren base\characters\Elise\emotions\button9_on.png button2_on.png

echo "Nightmare Update Completed"
pause
