rd /S /Q "base\characters\Klavier Wit"
del "base\characters\Blaise Debeste\emotions\button15_on.png"
del "base\characters\Blaise Debeste\emotions\button15_off.png"
del "base\characters\Blaise Debeste\emotions\button16_on.png"
del "base\characters\Blaise Debeste\emotions\button16_off.png"