del "base\sounds\music\[AOV] anime.opus"
del "base\sounds\music\[Misc] Deja Vu.opus"
del "base\sounds\music\[Misc] Running in the 90s.opus"
ren "base\sounds\music\[Misc] Infinite Edge.opus" "[SF] Infinite Edge.opus"
del "base\sounds\music\[Misc] Ocean Man.opus"
ren "base\sounds\music\[Misc] Pizza Time.opus" "[SM2] Pizza Time.opus"
del "base\sounds\music\[Misc] Stand Activated.opus"
ren "base\sounds\music\[Misc] What's the Deal with Contradictions.opus" "[S] What's the Deal with Contradictions.opus"
ren "base\sounds\music\[Misc] What is thinking.opus" "[J] What is thinking.opus"
del "base\sounds\music\[Misc] It is a Mystery.opus"
del "base\sounds\music\[Misc] YWRN.opus"
ren "base\sounds\music\[Misc] You're the Inspiration.opus" "[Ch] You're the Inspiration.opus"
ren "base\sounds\music\[Misc] Want You Gone.opus" "[JC] Want You Gone.opus"
ren "base\sounds\music\[Misc] Komm Susser Tod.opus" "[NGE] Komm Susser Tod.opus"
ren "base\sounds\music\[Misc] Bustin'.opus" "[NC] Spooky People.opus"
ren "base\sounds\music\[Misc] Law & Order - Main Theme.opus" "[L&O] Trial.opus"
ren "base\sounds\music\[Misc] Gas Gas Gas.opus" "[ID] Gas Gas Gas.opus"
del "base\sounds\music\[MGS5] Apollo Justice - Nuclear.opus"
del "base\sounds\music\[YES] Roundabout.opus"
ren "base\evidence\DGSCastHutch.png" "DGSCastHatch.png"
del "base\sounds\music\[GMO] Godot - The Fragrance of Dark Coffee.opus"
del "base\sounds\music\[GMO] Miles Edgeworth - Great Revival.opus"
rmdir /Q /S "base\characters\Dante"
rmdir /Q /S "base\characters\Calisto"
pause