del "base\sounds\music\[15th] Ema Skye - Scientific Detective.mp3"
del "base\sounds\music\[15th] Kay Faraday - The Great Truth Burglar.mp3"
del "base\sounds\music\[15th] Logic - The Way to the Truth.mp3"
del "base\sounds\music\[15th] Maya Fey - Turnabout Sisters.mp3"
del "base\sounds\music\[15th] Prelude to the Adventure.mp3"
del "base\sounds\music\[15th] Raymond Shields - Joking Motive.mp3"
del "base\sounds\music\[15th] Sebastian Debeste - Debeste Reasoning.mp3"
del "base\sounds\music\[15th] Trifle of Fate.mp3"
del "base\sounds\music\[AA] Objection! (15th).mp3"
del "base\sounds\music\[AA] Pursuit (Orchestra).mp3"
del "base\sounds\music\[AA] Questioning (15th).mp3"
del "base\sounds\music\[AAI2] Confrontation (Presto-15th).mp3"
del "base\sounds\music\[AAI2] Investigation (Core-15th).mp3"
del "base\sounds\music\[AAI2] Investigation (Middle-15th).mp3"
del "base\sounds\music\[AAI2] Little Thief (15th).mp3"
del "base\sounds\music\[AAI2] Objection! (15th).mp3"
del "base\sounds\music\[AAI2] Orchestral Confrontation.mp3"
del "base\sounds\music\[AAI2] Pursuit (15th).mp3"
del "base\sounds\music\[AAI2] Pursuit (Orchestra).mp3"
del "base\sounds\music\[AAI2] Pursuit (Unlimited).mp3"
del "base\sounds\music\[AAI2] The IS-7 Incident (Orchestra).mp3"
del "base\sounds\music\[AJ] Prosecutor Justice - A New Path.mp3"
del "base\sounds\music\[AJ] Pursuit (15th).mp3"
del "base\sounds\music\[AJ] Questioning (15th).mp3"
del "base\sounds\music\[AJ] The Guitar's Serenade (Piano).mp3"
del "base\sounds\music\[AJ] Trial (15th).mp3"
del "base\sounds\music\[Ani] April May - Beautiful Secretary.mp3"
del "base\sounds\music\[Ani] Ben and Trilo - The Ventriloquism of the Doll, Trilo.mp3"
del "base\sounds\music\[Ani] Cody Hackins - Path to Glory.mp3"
del "base\sounds\music\[Ani] Dawn of a Turnabout.mp3"
del "base\sounds\music\[Ani] Dick Gumshoe - Noodles And Paycuts.mp3"
del "base\sounds\music\[Ani] Edgeworth's Distress.mp3"
del "base\sounds\music\[Ani] Larry Butz - It's Usually the Butz.mp3"
del "base\sounds\music\[Ani] Lotta Hart - The Photographer from the South.mp3"
del "base\sounds\music\[Ani] Max Galactica - Gorgeous!.mp3"
del "base\sounds\music\[Ani] Objection!.mp3"
del "base\sounds\music\[Ani] Objection! (Variation).mp3"
del "base\sounds\music\[Ani] Pearl Fey - Playful Pearl.mp3"
del "base\sounds\music\[Ani] Phoenix Wright - Novice Attorney Phoenix!.mp3"
del "base\sounds\music\[Ani] Pursuit.mp3"
del "base\sounds\music\[Ani] Questioning (Allegro).mp3"
del "base\sounds\music\[Ani] Questioning (Moderato).mp3"
del "base\sounds\music\[Ani] Reasoning in a Pinch.mp3"
del "base\sounds\music\[Ani] Shelly de Killer - Fear of de Killer.mp3"
del "base\sounds\music\[Ani] Suspense.mp3"
del "base\sounds\music\[Ani] Trial.mp3"
del "base\sounds\music\[Ani] Victory!
del "base\sounds\music\[Ani] Wendy Oldbag - Darn Whippersnappers!.mp3"
del "base\sounds\music\[Ba] Venus - Your Desire.mp3"
del "base\sounds\music\[CB] Blue.mp3"
del "base\sounds\music\[DD] Pursuit (15th).mp3"
del "base\sounds\music\[DD] Pursuit (Demo Remix).mp3"
del "base\sounds\music\[DD] Pursuit (Unlimited).mp3"
del "base\sounds\music\[DD] Questioning (Allegro-15th).mp3"
del "base\sounds\music\[DD] Questioning (Moderato-15th).mp3"
del "base\sounds\music\[DGS] Closing Suite (15th).mp3"
del "base\sounds\music\[DGS] Objection! (15th).mp3"
del "base\sounds\music\[DGS] Pursuit (15th).mp3"
del "base\sounds\music\[DGS] Questioning (15th).mp3"
del "base\sounds\music\[DGS2] Solo of Rage (DLC).mp3"
del "base\sounds\music\[DN] Ideological People.mp3"
del "base\sounds\music\[DN] Note Logic.mp3"
del "base\sounds\music\[DP] Comic People.mp3"
del "base\sounds\music\[DP] Confess the Truth.mp3"
del "base\sounds\music\[DP] Investigation (Core).mp3"
del "base\sounds\music\[DP] Investigation (Opening).mp3"
del "base\sounds\music\[DP] Pillow Stains.mp3"
del "base\sounds\music\[EO] Juniper Woods - Cerulean Woods.mp3"
del "base\sounds\music\[EO] Pursuit.mp3"
del "base\sounds\music\[EO] Questioning (Allegro).mp3"
del "base\sounds\music\[FE] Objection! (Fire).mp3"
del "base\sounds\music\[FE] Pursuit (Dark).mp3"
del "base\sounds\music\[GMO] Epilogue.mp3"
del "base\sounds\music\[GMO] Investigation.mp3"
del "base\sounds\music\[GMO] Kurain Genealogy.mp3"
del "base\sounds\music\[GMO] Maya Fey - Turnabout Sisters.mp3"
del "base\sounds\music\[GMO] Objection!.mp3"
del "base\sounds\music\[GMO] Objection! (Apollo).mp3"
del "base\sounds\music\[GMO] The Steel Samurai - Warrior of Neo Olde Tokyo.mp3"
del "base\sounds\music\[GSM] Questioning (Allegro).mp3"
del "base\sounds\music\[HB] Harvey Birdman - Attorney At Law.mp3"
del "base\sounds\music\[HeH] Neil Marshall - Fastest Prosecution in the West.mp3"
del "base\sounds\music\[JFA] Objection! (15th).mp3"
del "base\sounds\music\[JFA] Pursuit (Orchestra).mp3"
del "base\sounds\music\[JFA] Questioning (15th).mp3"
del "base\sounds\music\[JFA] Questioning (Orchestra).mp3"
del "base\sounds\music\[JFA] Trial (15th).mp3"
del "base\sounds\music\[JFA] Trial (Orchestra).mp3"
del "base\sounds\music\[K64] VS. Zero Two.mp3"
del "base\sounds\music\[K7] Olga Orly - Russian Roulette.mp3"
del "base\sounds\music\[KA] Questioning (Presto).mp3"
del "base\sounds\music\[LS] Confess The Truth.mp3"
del "base\sounds\music\[M&L3] Confrontation (Presto).mp3"
del "base\sounds\music\[Misc] Mod Exam - Examination.mp3"
del "base\sounds\music\[Misc] Mod Exam - Virtue, Efficiency, Responsibility.mp3"
del "base\sounds\music\[Misc] Routine.mp3"
del "base\sounds\music\[Mov] Necessary Measure.mp3"
del "base\sounds\music\[Mov] Objection!.mp3"
del "base\sounds\music\[Mov] Suspense (Gambling).mp3"
del "base\sounds\music\[Mov] Trial.mp3"
del "base\sounds\music\[Mov] Unjust Enrichment.mp3"
del "base\sounds\music\[Mov] Victory!.mp3"
del "base\sounds\music\[O] Pursuit.mp3"
del "base\sounds\music\[O] Sleep my Dear.mp3"
del "base\sounds\music\[O] The Chain.mp3"
del "base\sounds\music\[P4U] Margaret - Poem for Everyone's Souls.mp3"
del "base\sounds\music\[PS2] Smooth People.mp3"
del "base\sounds\music\[PWC] The Steel Samurai - Warrior of Neo Olde Tokyo.mp3"
del "base\sounds\music\[PXZ2] Pursuit.mp3"
del "base\sounds\music\[RG] Logic and Strategy.mp3"
del "base\sounds\music\[RG] Questioning (Allegro).mp3"
del "base\sounds\music\[RG] Questioning (Moderato).mp3"
del "base\sounds\music\[RG] Sweet Memories.mp3"
del "base\sounds\music\[RG] Trial.mp3"
del "base\sounds\music\[RT] Infiltrating the Parisian City Police.mp3"
del "base\sounds\music\[RT] Objection!.mp3"
del "base\sounds\music\[RT] Questioning (Moderato).mp3"
del "base\sounds\music\[RT] Rowdy People.mp3"
del "base\sounds\music\[RT] Victory!.mp3"
del "base\sounds\music\[SF] Guile.mp3"
del "base\sounds\music\[SH] Caeser Villan - Who Let The Dogs Out.mp3"
del "base\sounds\music\[SJ] Intelligent People.mp3"
del "base\sounds\music\[SJ] Philosophical People.mp3"
del "base\sounds\music\[SMT] Regal Crisis.mp3"
del "base\sounds\music\[SMTSJ] Questioning (Allegro).mp3"
del "base\sounds\music\[SMTSJ] Questioning (Moderato).mp3"
del "base\sounds\music\[SoJ] Objection! (Phoenix-15th).mp3"
del "base\sounds\music\[SoJ] Pursuit (15th).mp3"
del "base\sounds\music\[SoJ] Questioning (Allegro-15th).mp3"
del "base\sounds\music\[SoJ] Questioning (Moderato-15th).mp3"
del "base\sounds\music\[SoJ] Trial (Japanifornia-15th).mp3"
del "base\sounds\music\[SotC] Confess The Truth.mp3"
del "base\sounds\music\[SotC] Prelude.mp3"
del "base\sounds\music\[T&T] Pursuit (15th).mp3"
del "base\sounds\music\[T&T] Pursuit (Orchestra).mp3"
del "base\sounds\music\[T&T] Questioning (15th).mp3"
del "base\sounds\music\[T&T] Questioning (Orchestra).mp3"
del "base\sounds\music\[TAJ] Luis Hawk - Judge, Jury and Executioner.mp3"
del "base\sounds\music\[U] Suspense.mp3"
del "base\sounds\music\[UF] Questioning (Allegro).mp3"
del "base\sounds\music\[UF] Questioning (Moderato).mp3"
del "base\sounds\music\[UMvC3] Objection!.mp3"
del "base\sounds\music\[UMvC3] Pursuit.mp3"
del "base\sounds\music\[WL] Warden Mundy - Rock the Outback.mp3"
del "base\sounds\music\[15th] Iris Watson - A Little Biographer.mp3"
del "base\sounds\music\[15th] The Steel Samurai - Warrior of Neo Olde Tokyo.mp3"
del "base\sounds\music\[AAI] Pursuit (Unlimited).mp3"
del "base\sounds\music\[Ani] Opening Season 2.mp3"
del "base\sounds\music\[Ani] The Steel Samurai - Warrior of Neo Olde Tokyo.mp3"
del "base\sounds\music\[Brexit] EU Remover.mp3"
del "base\sounds\music\[DD] Trial (15th).mp3"
del "base\sounds\music\[DGS] Pursuit (Unlimited).mp3"
del "base\sounds\music\[DGS] Robert Crogley - Unhand Me, Filthy Urchin!.mp3"
del "base\sounds\music\[FE] Miscreant.mp3"
del "base\sounds\music\[FE] Prelude to Dispute.mp3"
del "base\sounds\music\[JFA] Pursuit (Unlimited).mp3"
del "base\sounds\music\[LT] Pursuit.mp3"
del "base\sounds\music\[MGS5] Punished People.mp3"
del "base\sounds\music\[Misc] 3DKH.mp3"
del "base\sounds\music\[Misc] Ass.mp3"
del "base\sounds\music\[Misc] Birds.mp3"
del "base\sounds\music\[Misc] Bubblegum Bitch.mp3"
del "base\sounds\music\[Mov] Investigation (Core).mp3"
del "base\sounds\music\[Mov] Maya Fey - Turnabout Sisters (Choir).mp3"
del "base\sounds\music\[Mov] Pursuit.mp3"
del "base\sounds\music\[Mov] Questioning (Allegro).mp3"
del "base\sounds\music\[Mov] Symphonic Regrets.mp3"
del "base\sounds\music\[Mov] The Steel Samurai - Warrior of Neo Olde Tokyo.mp3"
del "base\sounds\music\[PLvsAA] Pursuit (Unlimited).mp3"
del "base\sounds\music\[PS2] Delia Kartmann ~ Poker Night.mp3"
del "base\sounds\music\[SA2] Pumpkin People.mp3"
del "base\sounds\music\[SMBM] Questioning (Presto)
del "base\sounds\music\[SMTSJ] Questioning (Presto)
del "base\sounds\music\[SoJ] Pursuit (Unlimited)
del "base\sounds\music\[SoS] Rydia - A Dance of Autumn
del "base\sounds\music\[T&T] Pursuit (Unlimited)