rd /S /Q "base\characters\Darklaw"
rd /S /Q "base\characters\AthenaH"
rd /S /Q "base\characters\Bikini and Elise"
del "base\characters\Angie\dead.gif"
del "base\characters\Kira\(a)flowerpickling.gif"
del "base\characters\Kira\(b)flowerpickling.gif"
del "base\characters\Kira\pre-flowerpickling.gif"
del "base\characters\Kira\pre-flowerpickling-tn.gif"
del "base\sounds\music\[MOD] Clover.mp3"
del "base\sounds\music\[MOD] Lestrade.mp3"
del "base\sounds\music\[MOD] Brother.mp3"
del "base\sounds\music\[MOD wake me up.mp3"