rd /S /Q "base\characters\Darklaw"
rd /S /Q "base\characters\AthenaH"
rd /S /Q "base\characters\Bikini and Elise"
rd /S /Q "base\characters\Apollo 3D"
rd /S /Q "base\characters\Barok"
rd /S /Q "base\characters\Ema2"
rd /S /Q "base\characters\Vera"
rd /S /Q "base\characters\Cammy\Cammy"
rd /S /Q "base\characters\Alita Tiala\demothings"
rd /S /Q "base\characters\Alita Tiala\Emotion"

del "base\characters\Angie\dead.gif"

del "base\characters\Kira\(a)flowerpickling.gif"
del "base\characters\Kira\(b)flowerpickling.gif"
del "base\characters\Kira\pre-flowerpickling.gif"
del "base\characters\Kira\pre-flowerpickling-tn.gif"

del "base\sounds\music\[MOD] Clover.mp3"
del "base\sounds\music\[MOD] Lestrade.mp3"
del "base\sounds\music\[MOD] Brother.mp3"
del "base\sounds\music\[MOD] wake me up.mp3"

del "base\characters\Ace\acebigsmile.gif"
del "base\characters\Ace\acefrustrated.gif"
del "base\characters\Ace\acesad.gif"
del "base\characters\Ace\acescary.gif"
del "base\characters\Ace\aceserious.gif"
del "base\characters\Ace\acescary.gif"
del "base\characters\Ace\acesmile.gif"
del "base\characters\Ace\acesurprised.gif"
del "base\characters\Ace\acesmile.gif"

del "base\characters\Butz\guardnormal.gif"
del "base\characters\Butz\lauricenormal.gif"

del "base\characters\Cammy\sweaty(a).gif"
del "base\characters\Cammy\sweaty(b).gif"

del "base\characters\Cody\grin.gif"
del "base\characters\Cody\grumpy.gif"
del "base\characters\Cody\mad.gif"
del "base\characters\Cody\smug.gif"
del "base\characters\Cody\sniff.gif"

del "base\characters\Colias Palaeno\(a)dhee.gif"
del "base\characters\Colias Palaeno\(b)dhee.gif"
del "base\characters\Colias Palaeno\(a)dnormal.gif"
del "base\characters\Colias Palaeno\(b)dnormal.gif"
del "base\characters\Colias Palaeno\(a)dohdear.gif"
del "base\characters\Colias Palaeno\(b)dohdear.gif"
del "base\characters\Colias Palaeno\(a)dsaywhaat.gif"
del "base\characters\Colias Palaeno\(b)dsaywhaat.gif"
del "base\characters\Colias Palaeno\(a)dserious.gif"
del "base\characters\Colias Palaeno\(b)dserious.gif"
del "base\characters\Colias Palaeno\(a)dsweat.gif"
del "base\characters\Colias Palaeno\(b)dsweat.gif"

del "base\characters\Desiree\desiree-happy.gif"
del "base\characters\Desiree\desiree-normal(a).gif"
del "base\characters\Desiree\desiree-normal(b).gif"
del "base\characters\Desiree\desireenormal.gif"
del "base\characters\Desiree\desiree-normal.gif"
del "base\characters\Desiree\desiree-smile.gif"
del "base\characters\Desiree\desiree-sweating(a).gif"
del "base\characters\Desiree\desiree-sweating(b).gif"
del "base\characters\Desiree\desireesweating.gif"
del "base\characters\Desiree\desiree-thinking(a).gif"
del "base\characters\Desiree\desiree-thinking(b).gif"
del "base\characters\Desiree\desireethinking.gif"
