
del "base\characters\Franziska"
del "base\characters\April"
del "base\characters\Baliff" "JP"
del "base\characters\Baliff" "GB"
del "base\characters\Maggey"
del "base\characters\Maggey" "AAI"
del "base\characters\Olga" "Orly"
del "base\characters\Pearl"
del "base\characters\Cammy\(b)LSP.gif"
del "base\characters\Cammy\(a)LSP.gif"
del "base\characters\Adrian\(b)LSP.gif"
del "base\characters\Adrian\(a)LSP.gif"
del "base\characters\Rhoda" "Teneiro\(b)LSP.gif"
del "base\characters\Rhoda" "Teneiro\(a)LSP.gif"
del "base\characters\Alice\(b)helping_clover.gif"
del "base\characters\Alice\(a)helping_clover.gif"
del "base\characters\Tenmyouji\(a)hugging_quark.gif"
del "base\characters\Tenmyouji\(b)hugging_quark.gif"

del "base\characters\Yew\(a)shigrin.gif"
del "base\characters\Yew\(b)shigrin.gif"
del "base\characters\Yew\(b)shinormal.gif"
del "base\characters\Yew\(a)shinormal.gif"
del "base\characters\Yew\(b)shinormalglasses.gif"
del "base\characters\Yew\(a)shinormalglasses.gif"
del "base\characters\Yew\(b)shipapers.gif"
del "base\characters\Yew\(a)shipapers.gif"
del "base\characters\Yew\(b)shismile.gif"
del "base\characters\Yew\(a)shismile.gif"
del "base\characters\Yew\(b)shisweat.gif"
del "base\characters\Yew\(a)shisweat.gif"
del "base\characters\Yew\(b)shitilt.gif"
del "base\characters\Yew\(a)shitilt.gif"
del "base\characters\Yew\shibow.gif"
del "base\characters\Yew\shibreakdown.gif"
del "base\characters\Yew\shidamage.gif"
del "base\characters\Yew\doublepoint.gif"
del "base\characters\Yew\shilaugh.gif"
del "base\characters\Yew\shipoint.gif"
del "base\characters\Yew\(b)shiremove.gif"

del "base\characters\Cammy\emotions\button27_off.png"
del "base\characters\Cammy\emotions\button27_on.png"
del "base\characters\Tenmyouji\emotions\button11_on.png"
del "base\characters\Tenmyouji\emotions\button11_off.png"
del "base\characters\Alice\emotions\button13_on.png"
del "base\characters\Alice\emotions\button13_off.png"
del "base\characters\Yew\emotions\button17_off.png"
del "base\characters\Yew\emotions\button17_on.png"
del "base\characters\Yew\emotions\button18_off.png"
del "base\characters\Yew\emotions\button18_on.png"
del "base\characters\Yew\emotions\button19_off.png"
del "base\characters\Yew\emotions\button19_on.png"
del "base\characters\Yew\emotions\button20_off.png"
del "base\characters\Yew\emotions\button20_on.png"
del "base\characters\Yew\emotions\button21_off.png"
del "base\characters\Yew\emotions\button21_on.png"
del "base\characters\Yew\emotions\button22_off.png"
del "base\characters\Yew\emotions\button22_on.png"
del "base\characters\Yew\emotions\button23_off.png"
del "base\characters\Yew\emotions\button23_on.png"
del "base\characters\Yew\emotions\button24_off.png"
del "base\characters\Yew\emotions\button24_on.png"
del "base\characters\Yew\emotions\button25_off.png"
del "base\characters\Yew\emotions\button25_on.png"
del "base\characters\Yew\emotions\button26_off.png"
del "base\characters\Yew\emotions\button26_on.png"


del "base\sounds\music\[BB] Dangerous People.mp3"
del "base\sounds\music\[BB] Malicious People.mp3"
del "base\sounds\music\[DGS] Closing Suite.mp3"
del "base\sounds\music\[DGS] Confess the Truth.mp3"
del "base\sounds\music\[DGS] Investigation.mp3"
del "base\sounds\music\[DGS] London - Business as Usual.mp3"
del "base\sounds\music\[TWEWY] Sho Minamoto - So Zetta Slow!.mp3"

del "base\sounds\sounds\general\sfx-con-damage.wav"

rd /S /Q "base\characters\Justine" "CourtneyPro"

echo "completed"
exit
